tasks:
  - name: Front Terminal
    openMode: tab-before
    command: cd frontend

  - name: Back Terminal
    openMode: tab-before
    command: cd backend

  - name: Frontend
    before: npm install -g @angular/cli
    init: cd frontend && npm install
    command: cd frontend && npm run gitpod-start

  - name: Backend
    openMode: tab-after
    init: cd backend && composer install
    command: |
      php backend/bin/console d:d:d
      php backend/bin/console d:m:m --no-interaction
      php backend/bin/console d:d:d --env=test
      php backend/bin/console d:m:m --no-interaction --env=test
      php -S 0.0.0.0:8000 -t backend/public/

ports:
  - port: 4200
    onOpen: open-browser
    visibility: public
  - port: 8000
    visibility: public
